language: node_js

node_js:
  - 9
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install

before_script:
  - yarn start -- --silent &

script:
  - yarn build
  - yarn run cypress:run
  - yarn test

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: react-sep-pr-$TRAVIS_PULL_REQUEST.surge.sh
